name: Build & Publish

on:
  push:
    tags:
      - 'v*.*.*'          # 只要推含 vX.Y.Z 標籤就觸發

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. 取回程式碼
      - uses: actions/checkout@v4

      # 2. Node + npm registry 登入
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: npm

      # 3. 安裝相依（library 沒 lockfile → 用 install）
      - run: npm install --no-audit --no-fund

      # 4. 打包 – 輸出到 dist/guangxun-breadcrumb
      - run: npx ng-packagr -p ng-package.json

      # 5. 發佈到 npm
      - run: npm publish ./dist/guangxun-breadcrumb --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}